export const content = {
  vi: {
    nav: {
      home: "Trang chủ",
      about: "Giới thiệu",
      projects: "Dự án",
      resources: "Tài nguyên",
      contact: "Liên hệ",
    },
    home: {
      title: "Freelancer Esports Media || Esports Event Operations Associate",
      introduction: "Tạo ra những câu chuyện hình ảnh hấp dẫn, kết hợp thẩm mỹ tương lai với các nguyên tắc thiết kế vượt thời gian. Chào mừng đến với khu vườn sáng tạo neon của tôi.",
      exploreWork: "Khám phá tác phẩm",
      basicInfo: {
        title: "Thông tin",
        highlight: "Cơ bản",
        jobTitle: "Chức danh",
        fieldOfStudy: "Lĩnh vực học",
        dateOfBirth: "Ngày sinh",
        phone: "Điện thoại",
        address: "Địa chỉ",
      },
      experience: {
        title: "Kinh",
        highlight: "nghiệm",
      },
      callToAction: {
        title: "Hãy cùng tạo nên điều",
        highlight: "phi thường",
        description: "Có dự án trong đầu? Tôi luôn sẵn sàng cho những sự hợp tác mới và những thử thách thú vị.",
        button: "Liên hệ",
      },
    },
    about: {
      philosophyTitle: "Triết lý thiết kế của tôi",
      philosophyP1: "Tôi tin rằng thiết kế là một công cụ mạnh mẽ để giao tiếp và giải quyết vấn đề. Công việc của tôi được thúc đẩy bởi niềm đam mê tạo ra những trải nghiệm không chỉ tuyệt đẹp về mặt hình ảnh mà còn trực quan, ý nghĩa và dễ tiếp cận với mọi người. Tôi phát triển mạnh mẽ trước thách thức biến những ý tưởng phức tạp thành các giải pháp đơn giản, thanh lịch.",
      philosophyP2: "Lấy cảm hứng từ năng lượng sôi động của cyberpunk và vẻ đẹp tinh tế của thiên nhiên, tôi hướng tới việc tạo ra một thẩm mỹ 'khu vườn neon' độc đáo. Sự kết hợp giữa tổng hợp và hữu cơ này cho phép tôi khám phá các chủ đề về sự phát triển, công nghệ và tương lai của giao tiếp hình ảnh.",
      downloadResume: "Tải xuống CV của tôi",
      educationTitle: "Học",
      educationHighlight: "vấn",
      skillsTitle: "Kỹ",
      skillsHighlight: "năng của tôi",
      contactTitle: "Hãy cùng nhau xây dựng",
      contactHighlight: "Tương lai",
      contactDescription: "Tôi hiện đang sẵn sàng cho các dự án tự do và cơ hội làm việc toàn thời gian. Nếu bạn có một ý tưởng muốn thảo luận, tôi rất mong được nghe từ bạn.",
      contactButton: "Liên hệ với tôi",
    },
    projects: {
        title: "Tác phẩm của tôi",
        description: "Một tập hợp các dự án thể hiện niềm đam mê của tôi đối với việc xây dựng thương hiệu, minh họa và chỉ đạo nghệ thuật.",
        viewProject: "Xem dự án",
    },
    projectDetail: {
        aboutTitle: "Về dự án",
        principlesTitle: "Nguyên tắc thiết kế",
        behanceButton: "Xem trên Behance",
        critiqueTitle: "Phê bình thiết kế bằng AI",
        critiqueDescription: "Nhận một bài phê bình do AI tạo ra cho dự án này. Bạn có thể chỉnh sửa các chi tiết bên dưới để tinh chỉnh bài phê bình.",
        critiqueForm: {
            nameLabel: "Tên dự án",
            descriptionLabel: "Mô tả dự án",
            principlesLabel: "Nguyên tắc thiết kế",
            generateButton: "Tạo phê bình",
            generatingButton: "Đang tạo...",
            resultTitle: "Kết quả phê bình",
        },
    },
    resources: {
        title: "Trung tâm tài nguyên",
        description: "Một bộ sưu tập các công cụ, trang web và tài nguyên yêu thích của tôi cho thiết kế và sáng tạo.",
        loading: "Đang tải tài nguyên...",
    },
    contact: {
        title: "Liên hệ với tôi",
        description: "Tôi luôn sẵn sàng thảo luận về các dự án mới, ý tưởng sáng tạo hoặc cơ hội trở thành một phần trong tầm nhìn của bạn.",
        getInTouch: "Giữ liên lạc",
        followMe: "Theo dõi tôi",
        formTitle: "Gửi tin nhắn cho tôi",
        formName: "Tên của bạn",
        formEmail: "Email của bạn",
        formMessage: "Tin nhắn của bạn",
        formSend: "Gửi tin nhắn",
    },
    footer: {
      builtBy: "Xây dựng bởi",
      reserved: "Bản quyền.",
    },
    notFound: {
        title: "Lạc trong vườn Neon",
        description: "Xin lỗi, trang bạn đang tìm kiếm không tồn tại.",
        goHome: "Trở về trang chủ",
        contactSupport: "Liên hệ hỗ trợ",
    },
  },
  en: {
    nav: {
      home: "Home",
      about: "About",
      projects: "Projects",
      resources: "Resources",
      contact: "Contact",
    },
    home: {
      title: "Freelancer Esports Media || Esports Event Operations Associate",
      introduction: "Crafting compelling visual narratives that blend futuristic aesthetics with timeless design principles. Welcome to my neon garden of creativity.",
      exploreWork: "Explore My Work",
      basicInfo: {
        title: "Basic",
        highlight: "Information",
        jobTitle: "Title",
        fieldOfStudy: "Field of Study",
        dateOfBirth: "Date of Birth",
        phone: "Phone",
        address: "Address",
      },
      experience: {
        title: "Exper",
        highlight: "ience",
      },
      callToAction: {
        title: "Let's Create Something",
        highlight: "Extraordinary",
        description: "Have a project in mind? I'm always open to new collaborations and exciting challenges.",
        button: "Get in Touch",
      },
    },
    about: {
      philosophyTitle: "My Design Philosophy",
      philosophyP1: "I believe design is a powerful tool for communication and problem-solving. My work is driven by a passion for creating experiences that are not only visually stunning but also intuitive, meaningful, and accessible to everyone. I thrive on the challenge of transforming complex ideas into simple, elegant solutions.",
      philosophyP2: "Inspired by the vibrant energy of cyberpunk and the delicate beauty of nature, I aim to create a unique 'neon garden' aesthetic. This fusion of the synthetic and the organic allows me to explore themes of growth, technology, and the future of visual communication.",
      downloadResume: "Download My Resume",
      educationTitle: "Edu",
      educationHighlight: "cation",
      skillsTitle: "My",
      skillsHighlight: "Skills",
      contactTitle: "Let's Build the",
      contactHighlight: "Future",
      contactDescription: "I'm currently available for freelance projects and full-time opportunities. If you have an idea you'd like to discuss, I'd love to hear from you.",
      contactButton: "Contact Me",
    },
    projects: {
        title: "My Work",
        description: "A selection of projects that showcase my passion for branding, illustration, and art direction.",
        viewProject: "View Project",
    },
    projectDetail: {
        aboutTitle: "About the Project",
        principlesTitle: "Design Principles",
        behanceButton: "View on Behance",
        critiqueTitle: "AI Design Critique",
        critiqueDescription: "Get an AI-generated critique of this project. You can edit the details below to refine the critique.",
        critiqueForm: {
            nameLabel: "Project Name",
            descriptionLabel: "Project Description",
            principlesLabel: "Design Principles",
            generateButton: "Generate Critique",
            generatingButton: "Generating...",
            resultTitle: "Critique Result",
        },
    },
    resources: {
        title: "Resource Hub",
        description: "A curated collection of my favorite tools, websites, and resources for design and creativity.",
        loading: "Loading resources...",
    },
    contact: {
        title: "Contact Me",
        description: "I'm always open to discussing new projects, creative ideas, or opportunities to be part of your visions.",
        getInTouch: "Get in Touch",
        followMe: "Follow Me",
        formTitle: "Send me a message",
        formName: "Your Name",
        formEmail: "Your Email",
        formMessage: "Your Message",
        formSend: "Send Message",
    },
    footer: {
        builtBy: "Built by",
        reserved: "All rights reserved.",
    },
    notFound: {
        title: "Lost in the Neon Garden",
        description: "Sorry, the page you are looking for does not exist.",
        goHome: "Go back home",
        contactSupport: "Contact support",
    },
  },
};

    